export const TICK = "TICK";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";

export const SWITCH_CHARACTER = "SWITCH_CHARACTER";
export const FETCH_CHARACTER = "FETCH_CHARACTER";
export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAILTURE = "FETCH_CHARACTERS_FAILTURE";
